### ISSUE TITLE
Signed APK issue

### ISSUE THREAD

**Issue by Gagandeep1408** [noobcoder17/covid-19#2]
Getting Socket exception
![device-2020-11-18-115621](https://user-images.githubusercontent.com/59157362/99493364-1559ba80-2995-11eb-8c0b-73eb00800cf3.png)

**Comment by noobcoder17** [comment]
This is the issue of the Covid-19 data API. May be the API is updated. You
have to check.

Akash Debnath

**Comment by Gagandeep1408** [comment]
I've solved issue. 
Need to give internet permission in android menifest file.

**Comment by noobcoder17** [comment]
Great ,create a pull request. I will merge.

Akash Debnath

**Comment by Gagandeep1408** [comment]
just have a look into screenshot and add high lighted values
![image](https://user-images.githubusercontent.com/59157362/99494631-5c48af80-2997-11eb-8f65-6dcc3b9ea88a.png)

**Comment by noobcoder17** [comment]
Got it. 👍

Akash Debnath
